version: '3'
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: new_wave_dev_web
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: ["npm", "run", "start"]